include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - node_modules/**
    - test/**

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    always_use_package_imports: true
